# Generated by Django 4.1.7 on 2023-03-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
